// Raython Scaffolding Generator
// Rails-like code generation for W++ MVC framework

use std::fs;
use std::path::Path;
use colored::*;

/// Parse field definitions like "name:string age:i32"
fn parse_fields(fields_str: &str) -> Vec<(String, String)> {
    fields_str
        .split_whitespace()
        .filter_map(|f| {
            let parts: Vec<&str> = f.split(':').collect();
            if parts.len() == 2 {
                Some((parts[0].to_string(), parts[1].to_string()))
            } else {
                None
            }
        })
        .collect()
}

/// Generate a model file with validations
pub fn generate_model(name: &str, fields_str: &str) -> Result<(), String> {
    let fields = parse_fields(fields_str);

    // Capitalize model name
    let model_name = capitalize(name);
    let model_dir = Path::new("raython/models");
    fs::create_dir_all(model_dir)
        .map_err(|e| format!("Failed to create models directory: {}", e))?;

    let model_file = model_dir.join(format!("{}.wpp", name.to_lowercase()));

    let mut content = String::new();
    content.push_str(&format!("// {} Model\n", model_name));
    content.push_str(&format!("// Generated by W++ Raython Generator\n\n"));

    // Add field declarations
    for (field_name, field_type) in &fields {
        content.push_str(&format!("let {}_field = \"{}\"\n", field_name, field_name));
    }
    content.push_str("\n");

    // Generate validation function
    content.push_str(&format!("// Validate {} instance\n", model_name));
    content.push_str(&format!("func validate{}(", model_name));

    // Add parameters
    let params: Vec<String> = fields.iter()
        .map(|(name, ftype)| format!("{}: {}", name, ftype))
        .collect();
    content.push_str(&params.join(", "));
    content.push_str(") -> i32 {\n");
    content.push_str("    let errors = validation_errors_create()\n\n");

    // Add validation rules based on type
    for (field_name, field_type) in &fields {
        if field_type == "string" {
            content.push_str(&format!("    // Validate {}\n", field_name));
            content.push_str(&format!("    validate_presence({}, \"{}\", errors)\n", field_name, field_name));

            // Add length validation for string fields
            if field_name.contains("email") {
                content.push_str(&format!("    validate_email({}, \"{}\", errors)\n", field_name, field_name));
            } else if field_name.contains("url") || field_name.contains("website") {
                content.push_str(&format!("    validate_url({}, \"{}\", errors)\n", field_name, field_name));
            } else {
                content.push_str(&format!("    validate_length({}, \"{}\", 1, 255, errors)\n", field_name, field_name));
            }
            content.push_str("\n");
        } else if field_type == "i32" || field_type == "i64" {
            content.push_str(&format!("    // Validate {} range\n", field_name));
            content.push_str(&format!("    validate_number_range({}, \"{}\", 0, 999999, errors)\n\n", field_name, field_name));
        }
    }

    content.push_str("    if validation_errors_has(errors) == 1 {\n");
    content.push_str("        let error_json = validation_errors_get(errors)\n");
    content.push_str(&format!("        print(\"Validation errors for {}:\")\n", model_name));
    content.push_str("        print(error_json)\n");
    content.push_str("        return 0\n");
    content.push_str("    }\n\n");
    content.push_str("    return 1\n");
    content.push_str("}\n\n");

    // Generate create function
    content.push_str(&format!("// Create new {} instance\n", model_name));
    content.push_str(&format!("func create{}(", model_name));
    content.push_str(&params.join(", "));
    content.push_str(") -> i32 {\n");
    content.push_str(&format!("    print(\"Creating {}...\")\n", model_name));

    // Validate first
    content.push_str("    let is_valid = validate");
    content.push_str(&model_name);
    content.push_str("(");
    let field_names: Vec<String> = fields.iter().map(|(name, _)| name.clone()).collect();
    content.push_str(&field_names.join(", "));
    content.push_str(")\n\n");

    content.push_str("    if is_valid == 0 {\n");
    content.push_str("        return 0\n");
    content.push_str("    }\n\n");

    // Print saved fields
    for (field_name, _) in &fields {
        content.push_str(&format!("    print(\"{}: \", {})\n", capitalize(field_name), field_name));
    }

    content.push_str(&format!("\n    print(\"✅ {} created successfully\")\n", model_name));
    content.push_str("    return 1\n");
    content.push_str("}\n");

    fs::write(&model_file, content)
        .map_err(|e| format!("Failed to write model file: {}", e))?;

    println!("{} {}", "create".green(), model_file.display());
    Ok(())
}

/// Generate a controller with RESTful actions
pub fn generate_controller(name: &str) -> Result<(), String> {
    let controller_name = capitalize(name);
    let controller_dir = Path::new("raython/controllers");
    fs::create_dir_all(controller_dir)
        .map_err(|e| format!("Failed to create controllers directory: {}", e))?;

    let controller_file = controller_dir.join(format!("{}_controller.wpp", name.to_lowercase()));

    let mut content = String::new();
    content.push_str(&format!("// {} Controller\n", controller_name));
    content.push_str("// Generated by W++ Raython Generator\n\n");

    // Index action
    content.push_str(&format!("// GET /{} - List all {}\n", name.to_lowercase(), name.to_lowercase()));
    content.push_str(&format!("funcy {}Index() -> i32 {{\n", name.to_lowercase()));
    content.push_str(&format!("    print(\"GET /{}\")\n", name.to_lowercase()));
    content.push_str(&format!("    print(\"Listing all {}\")\n", name.to_lowercase()));
    content.push_str("    return 200\n");
    content.push_str("}\n\n");

    // Show action
    content.push_str(&format!("// GET /{}/:id - Show single {}\n", name.to_lowercase(), name));
    content.push_str(&format!("funcy {}Show(id: i32) -> i32 {{\n", name.to_lowercase()));
    content.push_str(&format!("    print(\"GET /{}/\", id)\n", name.to_lowercase()));
    content.push_str(&format!("    print(\"Showing {} with ID:\", id)\n", name));
    content.push_str("    return 200\n");
    content.push_str("}\n\n");

    // Create action
    content.push_str(&format!("// POST /{} - Create new {}\n", name.to_lowercase(), name));
    content.push_str(&format!("funcy {}Create(data: string) -> i32 {{\n", name.to_lowercase()));
    content.push_str(&format!("    print(\"POST /{}\")\n", name.to_lowercase()));
    content.push_str(&format!("    print(\"Creating new {} with data:\", data)\n", name));
    content.push_str("    return 201\n");
    content.push_str("}\n\n");

    // Update action
    content.push_str(&format!("// PUT /{}/:id - Update {}\n", name.to_lowercase(), name));
    content.push_str(&format!("funcy {}Update(id: i32, data: string) -> i32 {{\n", name.to_lowercase()));
    content.push_str(&format!("    print(\"PUT /{}/\", id)\n", name.to_lowercase()));
    content.push_str(&format!("    print(\"Updating {} with ID:\", id)\n", name));
    content.push_str("    print(\"New data:\", data)\n");
    content.push_str("    return 200\n");
    content.push_str("}\n\n");

    // Delete action
    content.push_str(&format!("// DELETE /{}/:id - Delete {}\n", name.to_lowercase(), name));
    content.push_str(&format!("funcy {}Destroy(id: i32) -> i32 {{\n", name.to_lowercase()));
    content.push_str(&format!("    print(\"DELETE /{}/\", id)\n", name.to_lowercase()));
    content.push_str(&format!("    print(\"Deleting {} with ID:\", id)\n", name));
    content.push_str("    return 204\n");
    content.push_str("}\n");

    fs::write(&controller_file, content)
        .map_err(|e| format!("Failed to write controller file: {}", e))?;

    println!("{} {}", "create".green(), controller_file.display());
    Ok(())
}

/// Generate a full scaffold (model + controller)
pub fn generate_scaffold(name: &str, fields_str: &str) -> Result<(), String> {
    println!("{}", format!("Generating scaffold for {}...", name).bright_cyan());

    // Create model
    generate_model(name, fields_str)?;

    // Create controller
    generate_controller(name)?;

    // Create test file
    generate_scaffold_test(name, fields_str)?;

    println!("\n{}", "Scaffold generated successfully!".green().bold());
    println!("\n{}", "Next steps:".yellow());
    println!("  1. Review generated files in raython/models/ and raython/controllers/");
    println!("  2. Run the test: wpp-cli run raython/tests/{}_test.wpp", name.to_lowercase());

    Ok(())
}

/// Generate a test file for the scaffold
fn generate_scaffold_test(name: &str, fields_str: &str) -> Result<(), String> {
    let fields = parse_fields(fields_str);
    let model_name = capitalize(name);

    let test_dir = Path::new("raython/tests");
    fs::create_dir_all(test_dir)
        .map_err(|e| format!("Failed to create tests directory: {}", e))?;

    let test_file = test_dir.join(format!("{}_test.wpp", name.to_lowercase()));

    let mut content = String::new();
    content.push_str(&format!("// {} Scaffold Test\n", model_name));
    content.push_str("// Generated by W++ Raython Generator\n\n");

    content.push_str("func main() {\n");
    content.push_str(&format!("    print(\"Testing {} Scaffold\")\n", model_name));
    content.push_str("    print(\"=\" * 40)\n");
    content.push_str("    print(\"\")\n\n");

    // Test model creation with sample data
    content.push_str("    // Test Model Creation\n");
    content.push_str(&format!("    print(\"Test 1: Create Valid {}\")\n", model_name));
    content.push_str("    print(\"-\" * 30)\n");

    // Generate sample values based on field types
    let sample_values: Vec<String> = fields.iter().map(|(field_name, field_type)| {
        if field_type == "string" {
            if field_name.contains("email") {
                "\"test@example.com\"".to_string()
            } else if field_name.contains("name") {
                format!("\"Sample {}\"", capitalize(field_name))
            } else {
                format!("\"Sample {}\"", field_name)
            }
        } else if field_type == "i32" || field_type == "i64" {
            if field_name.contains("age") {
                "25".to_string()
            } else if field_name.contains("price") {
                "999".to_string()
            } else {
                "42".to_string()
            }
        } else {
            "0".to_string()
        }
    }).collect();

    content.push_str(&format!("    let result1 = create{}({})\n", model_name, sample_values.join(", ")));
    content.push_str("    print(\"Result:\", result1)\n");
    content.push_str("    print(\"\")\n\n");

    // Test controller actions
    content.push_str("    // Test Controller Actions\n");
    content.push_str("    print(\"Test 2: Controller Index\")\n");
    content.push_str("    print(\"-\" * 30)\n");
    content.push_str(&format!("    let status1 = {}Index()\n", name.to_lowercase()));
    content.push_str("    print(\"Status:\", status1)\n");
    content.push_str("    print(\"\")\n\n");

    content.push_str("    print(\"Test 3: Controller Show\")\n");
    content.push_str("    print(\"-\" * 30)\n");
    content.push_str(&format!("    let status2 = {}Show(1)\n", name.to_lowercase()));
    content.push_str("    print(\"Status:\", status2)\n");
    content.push_str("    print(\"\")\n\n");

    content.push_str("    print(\"Test 4: Controller Create\")\n");
    content.push_str("    print(\"-\" * 30)\n");
    content.push_str(&format!("    let status3 = {}Create(\"sample data\")\n", name.to_lowercase()));
    content.push_str("    print(\"Status:\", status3)\n");
    content.push_str("    print(\"\")\n\n");

    content.push_str("    print(\"=\" * 40)\n");
    content.push_str(&format!("    print(\"✅ {} scaffold test complete!\")\n", model_name));
    content.push_str("    return 0\n");
    content.push_str("}\n");

    fs::write(&test_file, content)
        .map_err(|e| format!("Failed to write test file: {}", e))?;

    println!("{} {}", "create".green(), test_file.display());
    Ok(())
}

/// Generate a migration file
pub fn generate_migration(name: &str) -> Result<(), String> {
    let migration_dir = Path::new("raython/migrations");
    fs::create_dir_all(migration_dir)
        .map_err(|e| format!("Failed to create migrations directory: {}", e))?;

    // Generate timestamp-based filename
    use std::time::{SystemTime, UNIX_EPOCH};
    let timestamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .unwrap()
        .as_secs();

    let migration_file = migration_dir.join(format!("{}_{}.wpp", timestamp, name.to_lowercase()));

    let mut content = String::new();
    content.push_str(&format!("// Migration: {}\n", capitalize(name)));
    content.push_str("// Generated by W++ Raython Generator\n\n");

    content.push_str("// Run migration (up)\n");
    content.push_str("func up() {\n");
    content.push_str(&format!("    print(\"Running migration: {}\")\n", name));
    content.push_str("    // Add your migration code here\n");
    content.push_str("    // Example: create_table, add_column, etc.\n");
    content.push_str("}\n\n");

    content.push_str("// Rollback migration (down)\n");
    content.push_str("func down() {\n");
    content.push_str(&format!("    print(\"Rolling back migration: {}\")\n", name));
    content.push_str("    // Add your rollback code here\n");
    content.push_str("    // Example: drop_table, remove_column, etc.\n");
    content.push_str("}\n");

    fs::write(&migration_file, content)
        .map_err(|e| format!("Failed to write migration file: {}", e))?;

    println!("{} {}", "create".green(), migration_file.display());
    println!("{}", format!("Migration generated: {}", migration_file.display()).bright_cyan());

    Ok(())
}

/// Capitalize first letter of a string
fn capitalize(s: &str) -> String {
    let mut chars = s.chars();
    match chars.next() {
        None => String::new(),
        Some(first) => first.to_uppercase().collect::<String>() + chars.as_str(),
    }
}
