[package]
name = "wpp-cli"
version = "2.0.0-beta"
edition = "2021"
license = "MIT"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
colored = "2.1"
wpp-v2 = { path = "../wpp-v2" }
